### PR TITLE
Updating Javamail 1.5.5 -> 1.5.6 and Java 1.7 -> 1.8

### PR DESCRIPTION
**Pull request by csaltos**
Thank you for your library, it's very useful !!

### CODE REVIEW

**Comment by nithril** [comment]
Thanks for this pull request. 

The Java update is not necessary as the library doesn't use Java 8 feature and library client are not impeded to use their own version. I will integrate asap the Javamail update.

**Comment by csaltos** [comment]
Yes, good point, with Java 7 is enough. Thank you for the review.

**Comment by d4nirod** [comment]
Maybe this is not the best place to put this but anyway: thanks for making this open source. 
We've just deployed a new email handler for our task management/collaboration product which uses this library :crossed_fingers: 

A bit of advertising 😉: you're welcome to check it out at [cirkus.com](https://cirkus.com), we've just opened the beta to the public. Besides web there are also Mac and iOS clients.

**Comment by nithril** [comment]
Thanks @d4nirod.

The pull request is merged and the version 1.2.2 is deployed on maven central. Thanks for your contribution

**Pull request merged**
